# Generated by Django 4.2.2 on 2023-07-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
