# Generated by Django 4.2.2 on 2023-07-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_app', '0002_audiofile_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='Image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
