# Generated by Django 4.2.2 on 2023-07-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_app', '0003_audiofile_image_alter_audiofile_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
