# Generated by Django 4.2.2 on 2023-07-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_app', '0004_audiofile_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='duration',
        ),
    ]
