# Generated by Django 4.2.2 on 2023-07-03 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audio_app', '0005_remove_audiofile_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
